; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Thu Jun 03 2021 23:44:39 GMT-0400 (Eastern Daylight Time)

M671 ; Enable independent leadscrew adjustments
M561 ; clear any bed transform
G28  ; home all axes
G30 P0 X32 Y100 Z-99999 	; probe near a leadscrew, half way along Y axis
G30 P1 X198 Y100 Z-99999 S2 ; probe near a leadscrew and calibrate 2 motors
G29  ; probe the bed and enable compensation
