; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Thu Jun 03 2021 23:44:39 GMT-0400 (Eastern Daylight Time)
M280 P0 S90 ; retract BLTouch

