; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Thu Jun 03 2021 23:44:40 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P0

